{%- materialization fact, default -%}
    {% if config.get('lookback_window') is none %}
        {{ kimball._simple_fact() }}
    {% elif config.get('unique_expression') is none %}
        {{ kimball._complex_fact() }}
    {% else %}
        {{ kimball._accumulating_fact() }}
    {% endif %}

{% endmaterialization %}


{% macro _simple_fact() %}
    {% set model_dni = config.get('durable_natural_id_column', default='NULL') %}
    {% set model_instance_at = config.get('instance_at_column', default='NULL') %}

    -- get dim CTES
    {% call statement('dim_cte_meta', fetch_result=True, auto_begin=False) %}
        SELECT 
            fact_meta.dimension AS dimension
            ,COALESCE(fact_meta.instance_at_column, {{ model_instance_at }}, dimension_meta.cdc_column) AS instance_at_column
            ,COALESCE(fact_meta.dni_column, {{ model_dni }}, dimension_meta.dni_column) AS dni_column
        FROM
            {{ xdb.fold('dbt_kimball_staging.fact_meta') }} fact_meta
        LEFT JOIN
            {{ xdb.fold('dbt_kimball_staging.dimension_meta') }} dimension_meta
        USING (dimension)
        WHERE
            fact_meta.fact = '{{ this.table }}' 
    {% endcall %}
    {% set required_dims = load_result('dim_cte_meta')['data'] %}

    {% set sql_with_dim_joins %}
        {{ sql }}
        {% for dim in required_dims %}
        {% set dimension, instance_at, dni = dim %}
        JOIN
            (SELECT 
                {{ xdb.fold(dimension) }}_key
                ,{{ dni }}
                ,row_effective_at
                ,row_expired_at
             FROM
                {{ ref(dimension) }} ) AS {{ kimball._dbt_kimball_dim_key_helper( dimension ) }}
        USING ( {{ dni }} )
        WHERE 
            {{ instance_at }} 
        BETWEEN         
            {{ kimball._dbt_kimball_dim_key_helper( dimension ) }}.row_effective_at
        AND
            {{ kimball._dbt_kimball_dim_key_helper( dimension ) }}.row_expired_at
        {%  endfor %}
    {% endset %}

    {{ run_hooks(pre_hooks, inside_transaction=False) }}
    
    {{ run_hooks(pre_hooks, inside_transaction=True) }}

    {% call statement('main') %}
        {{ create_table_as(False,
                           this,
                           sql_with_dim_joins) }}
    {% endcall %}

    {% do adapter.commit() %}
    {{ run_hooks(post_hooks) }}

{% endmacro %}

{%- macro _dbt_kimball_dim_key_helper(dim)  -%}
    _dbt_kimball_{{ xdb.fold(dim) | trim }}_key_lookup
{%- endmacro -%}


{%- macro dim_date_key(column) -%}
    /*{# Less expensive magic for dim_dates.
    
        Since we use a human-readable key for dim date, we can shortcut here.

        Args:
            column (identifier) The name of the column to convert to a dim date key.
        
        Returns:
            partial: a sql string that converts ``column`` to a dim_date key.
    #}*/
    TO_CHAR({{ column }}, 'YYYYmmdd')
{%-  endmacro -%}

{%- macro dim_key(dim, alias=none, dni_column=none, instance_at_column=none) -%}
    /*{# uses "magic" to infer the dim key for a given fact.
        ARGS:
            dim (string): the only required param, this is the name of the inferred dimension
            alias (string): by default the dim key name is used, unless an alias  is provided here.
            dni_column (string): the name of the durable_natural_id shared between this fact and the dim.
                If not supplied it will use the fact config dni, then the dim dni (in that order).
            instance_at_column (string): the name of the date/timestamp of the fact event for SCD lookup.
                If not supplied it will use the fact config CDC, then the CDC dni (in that order). 
        RETURNS: a lookup key expecting the "magic" CTE generated by the fact.
    #}*/
    {%- call statement('insert_meta') -%}
        {{ kimball._kimball_insert_fact_meta(dim=dim,
                                             dni_column=dni_column,
                                             instance_at_column=instance_at_column) }}
    {%- endcall -%}
    -- depends on: {{ ref(dim) }}
    COALESCE(_dbt_kimball_{{ xdb.fold(dim) |trim }}_key_lookup.{{ xdb.fold(dim) |trim }}_key, -1) AS {{ alias if alias else xdb.fold(dim) ~ '_key' }} 
{%- endmacro -%}
