{%- macro _dbt_kimball_dim_key_helper(dim)  -%}
    _dbt_kimball_{{ xdb.fold(dim) | trim }}_key_lookup
{%- endmacro -%}



{%- macro dim_date_key(column) -%}
    /*{# Less expensive magic for dim_dates.
    
        Since we use a human-readable key for dim date, we can shortcut here.

        Args:
            column (identifier) The name of the column to convert to a dim date key.
        
        Returns:
            partial: a sql string that converts ``column`` to a dim_date key.
    #}*/
    TO_CHAR({{ column }}, 'YYYYmmdd')
{%-  endmacro -%}

{%- macro dim_key(dim, alias=none, dni_column=none, instance_at_column=none) -%}
    /*{# uses "magic" to infer the dim key for a given fact.
        ARGS:
            dim (string): the only required param, this is the name of the inferred dimension
            alias (string): by default the dim key name is used, unless an alias  is provided here.
            dni_column (string): the name of the durable_natural_id shared between this fact and the dim.
                If not supplied it will use the fact config dni, then the dim dni (in that order).
            instance_at_column (string): the name of the date/timestamp of the fact event for SCD lookup.
                If not supplied it will use the fact config CDC, then the CDC dni (in that order). 
        RETURNS: a lookup key expecting the "magic" CTE generated by the fact.
    #}*/
    {%- call statement('insert_meta') -%}
        {{ kimball._kimball_insert_fact_meta(dim=dim,
                                             dni_column=dni_column,
                                             instance_at_column=instance_at_column) }}
    {%- endcall -%}
    -- depends on: {{ ref(dim) }}
    COALESCE(_dbt_kimball_{{ xdb.fold(dim) |trim }}_key_lookup.{{ xdb.fold(dim) |trim }}_key, -1) AS {{ alias if alias else xdb.fold(dim) ~ '_key' }} 
{%- endmacro -%}
